name: Build And Release JASM Self Contained

on:
  push:
    tags:
      - "v*.*.*" # 匹配所有版本标签，例如 v1.0.0, v2.16.1 等

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Test
        run: dotnet test ${{ github.workspace }}\src

      - name: Build, publish and zip the app
        run: python ${{ github.workspace }}\Build\Release.py SelfContained ExcludeElevator
        shell: cmd

      - name: Upload JASM Self Contained to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}\${{ env.zipFile }}
          asset_name: JASM_Self_Contained.7z
          asset_content_type: application/x-7z-compressed
